version: "3"

tasks:
  dev:
    cmds:
      - air

  server:
    cmds:
      - go run ./cmd/server .

  client:
    cmds:
      - go run ./cmd/client .

  build-web-client:
    cmds:
      - env GOOS=js GOARCH=wasm go build -o ./.dist/web-client.wasm ./cmd/client/main.go
      - cp $(go env GOROOT)/misc/wasm/wasm_exec.js ./.dist
