version: "3"

tasks:
  dev:
    cmds:
      - air

  server:
    cmds:
      - go run ./cmd/server .

  client-desktop:
    cmds:
      - go run ./cmd/client-desktop .

  gomp-server:
    cmds:
      - go run ./pkgs/gomp/example/cmd/gomp-server .

  gomp-client:
    cmds:
      - go run ./pkgs/gomp/example/cmd/gomp-client .

  build-web-client:
    cmds:
      - env GOOS=js GOARCH=wasm go build -o ./.dist/web-client.wasm ./cmd/web-client-ws/main.go
      - cp $(go env GOROOT)/misc/wasm/wasm_exec.js ./.dist

  proto:
    cmds:
      - protoc --go_out=. internal/**/*.proto

  pprof:
    cmds:
      - go tool pprof -http=":8000" 'http://localhost:3000/debug/pprof/profile?seconds=10'
