name: Master Workflow

on:
  push:
    branches: [ main, feature/go-ci-pipeline ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  version-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        go-version: [ '1.23.5' ]
    uses: ./.github/workflows/go_ci.yml
    with:
      go-version: ${{ matrix.go-version }}
      os: ${{ matrix.os }}
